feat: add tokens for AgoraDex
pnetwork-association/ptokens-dapp pull request #86
Opened 2024-05-03 16:51 UTC by oliviera9

2024-05-06 09:45 UTC, envin3 requested changes
I would split the commit between actual features and tests.
Double checked decimal and they are correct.

2024-05-06 09:47 UTC, envin3 commented on src/settings/swap-assets.js
> +    address: 'eosio.token',
Is this address correct?

2024-05-06 09:47 UTC, envin3 commented on src/settings/swap-assets.js
> +    address: 'eosio.token',
address?

2024-05-06 09:47 UTC, envin3 commented on src/settings/swap-assets.js
> +    address: 'eosio.token',
address?

2024-05-06 09:47 UTC, oliviera9 commented on src/settings/swap-assets.js
> +    address: 'eosio.token',
Yes it is. For a confirmation, check PUOS_ON_ULTRA.

2024-05-06 13:04 UTC, envin3 approved these changes

2024-11-14 21:58 UTC, envin3 commented
v2 support dropped

2024-11-14 21:58 UTC, closed without merging